version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - derive
    ports:
      - "1235:1234"
    environment:
      - NODE_ENV=development
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
  api:
    build:
      context: ./eda
      dockerfile: Dockerfile
    container_name: api
    # entrypoint: [/bin/sh]
    stdin_open: true
    tty: true
    # command: [jupyter, notebook]
    networks:
      - derive
    ports:
      - "8888:8888"
    volumes:
      - ./eda:/eda
networks:
  derive:
